steps:
    # Step 0: Install DVC and pull data
    - name: python
      entrypoint: bash
      args: ['-c', 'mkdir ML-Ops-31; cd ML-Ops-31; pip install -U dvc dvc[gs];git init; dvc pull;']

    # Step 1: Build the Docker image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-f",
              "./dockerfiles/deploy_model_cloudbuild.dockerfile",
              ".",
              "-t",
              "gcr.io/dtu-ml-ops-31/deploy:latest"
          ]
           

    # Step 2: Push the Docker image to Artifact Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/dtu-ml-ops-31/deploy:latest"]

    # Step 3: Deploy the Docker image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
        ['run', 'deploy', 'deploy',
        '--image=gcr.io/dtu-ml-ops-31/deploy:latest',
        '--service-account=dtu-ml-ops-31@appspot.gserviceaccount.com',
        '--allow-unauthenticated',
        '--port=8080',
        '--cpu=2',
        '--memory=8Gi',
        '--max-instances=4',
        '--cpu-boost',
        '--region=us-central1',
        '--project=dtu-ml-ops-31'  ]


images:
    - "gcr.io/dtu-ml-ops-31/deploy:latest"

#'--service-account=1025735580781-compute@developer.gserviceaccount.com',

    
