steps:
    - name: python
      entrypoint: bash
      args: ['-c', 'mkdir ML-Ops-31; cd ML-Ops-31; pip install -U dvc dvc[gs];git init; dvc pull;']

    # Step 1: Build the Docker image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-f",
              "./dockerfiles/deploy_model_cloudbuild.dockerfile",
              ".",
              "-t",
              "gcr.io/dtu-ml-ops-31/deploy:latest"
          ]
           

    # Step 2: Push the Docker image to Artifact Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/dtu-ml-ops-31/deploy:latest"]




images:
    - "gcr.io/dtu-ml-ops-31/deploy:latest"


    
