# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/dtu-ml-ops-31/trainer:latest
        #command: ["python","-u","hatespeech_classification_02476/train_model.py experiments=exp2"]
        env:
            - name: WANDB_API_KEY
              value: 5747610627c177d2a50b01e49dc49c541a8e9156