name: CI-tests

on:
  push:

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use or setup cache cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements_dev.txt'

      - name: Install requirements_dev
        run: pip install -r requirements_dev.txt

      #- uses: iterative/setup-dvc@v1
      #- name: Get data
      #  run: dvc pull
      #  env:
      #    GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Run pytest for model
        run: pytest tests/test_model.py
      #  env:
      #    GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}  # Pass the necessary environment variable

      #- name: Run pytest for data
      #  run: pytest tests/test_data.py
      #  env:
      #    GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}  # Pass the necessary environment variable
